### PR TITLE
Set up workflow to publish Docker images

### PR DESCRIPTION
**Pull request by Scott-Guest**
- Copies the workflows and actions from https://github.com/runtimeverification/z3-images
- Sets up the Dockerfile to install riscv-gnu-toolchain
- Adds a smoke test

### CODE REVIEW

**Comment by Scott-Guest** [comment]
@Baltoli any ideas why the `test-pr` workflow isn't being run here?

**Comment by Baltoli** [comment]
Freeman will need to click a button:
Screenshot 2024-05-23 at 16 38 16

**Review by Baltoli — APPROVED** [review]
Looks good to me once we have actions running!

**Comment by FWBlueWizard** [comment]
Activated now, @Scott-Guest You'll need to kick it to start a run.

**Review by FWBlueWizard — APPROVED** [review]

**Comment by Baltoli** [comment]
@Scott-Guest it looks like the toolchain is too big to run on GitHub-hosted runners, so I've moved it over to self-hosted

**Comment by Baltoli** [comment]
You also probably need to `make install` in the workflow here (shame it takes so long to realise this!).

**Pull request merged**
